services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    env_file: ./secrets.env
    environment:
      # Configurazione Database automatica
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
    restart: always
    volumes:
      - /opt/gitea/data/gitea/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22" # Mappiamo la porta SSH interna 22 sulla 2222 esterna per non confliggere con l'host
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gitea_db
    restart: always
    env_file: ./secrets.env
    environment:
      POSTGRES_USER: gitea
      POSTGRES_DB: gitea
    volumes:
      - /opt/gitea/data/postgres:/var/lib/postgresql/data