---
- import_playbook: ../docker/docker.ansible.yml

- name: Install Gitea
  hosts: all
  become: true
  vars:
    base_dir: /opt/gitea

  tasks:
    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ base_dir }}/data"
        - "{{ base_dir }}/data/postgres"
        - "{{ base_dir }}/data/gitea"
        
    - name: Copy compose.yml
      copy:
        dest: "{{ base_dir }}/compose.yml"
        src: ./compose.yml

    - name: Copy secrets.env
      copy:
        dest: "{{ base_dir }}/secrets.env"
        src: ./secrets.env

    - name: Start Docker Compose Services
      command: docker compose -f "{{ base_dir }}/compose.yml" up -d
      args:
        chdir: "{{ base_dir }}"