---
- import_playbook: ../docker/docker.ansible.yml
    
- name: Install ExcaliDash
  hosts: all
  become: true
  vars:
    base_dir: /opt/excalidash
  tasks:
    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ base_dir }}/data"
        
    - name: Copy compose.yml
      copy:
        dest: "{{ base_dir }}/compose.yml"
        src: ./compose.yml

    - name: Copy .env
      copy:
        dest: "{{ base_dir }}/.env"
        src: ./.env

    - name: Start Docker Compose Services
      command: docker compose -f "{{ base_dir }}/compose.yml" up -d
      args:
        chdir: "{{ base_dir }}"