---
- import_playbook: ../docker/docker.ansible.yml
    
- name: Install PeaNUT
  hosts: all
  become: true
  vars:
    base_dir: /opt/peanut

  tasks:
    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ base_dir }}/config"
        
    - name: Copy compose.yml
      copy:
        dest: "{{ base_dir }}/compose.yml"
        src: ./compose.yml
    
    - name: Start Docker Compose Services
      command: docker compose -f "{{ base_dir }}/compose.yml" up -d
      args:
        chdir: "{{ base_dir }}"